# Request
string text_command
sensor_msgs/Image[] observations_main
sensor_msgs/Image[] observations_wrist
sensor_msgs/Image[] goal_images
---
# Response
geometry_msgs/Vector3 linear
geometry_msgs/Vector3 angular
bool gripper